// <auto-generated />
using System;
using Actividad.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Actividad.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Actividad.Data.Entities.Estacionamiento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Calificacion")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estacionamientos");

                    b
                        .HasComment("Producto del servicio");

                    b.HasData(
                        new
                        {
                            Id = "2a209976-f965-4850-8a5d-c5ebfc9887eb",
                            Calificacion = 5m,
                            Calle = "A",
                            CodigoPostal = "28001",
                            Colonia = "Colonia A",
                            Costo = 15m,
                            Descripcion = "El más barato de revolución",
                            Latitud = "19.239937687163206",
                            Longitud = "-103.7237955329542",
                            Municipio = "Colima",
                            Nombre = "Revolucionario",
                            Numero = "1"
                        },
                        new
                        {
                            Id = "237216dc-cff4-492f-a0ac-68c65c74ced7",
                            Calificacion = 5m,
                            Calle = "B",
                            CodigoPostal = "28002",
                            Colonia = "Colonia B",
                            Costo = 15m,
                            Descripcion = "Ecoestacionamiento reformado",
                            Latitud = "19.24303615160122",
                            Longitud = "-103.72825568830704",
                            Municipio = "Colima",
                            Nombre = "Libertad",
                            Numero = "2"
                        },
                        new
                        {
                            Id = "e24fd53a-37af-4beb-842d-61646bfb20f4",
                            Calificacion = 4.8m,
                            Calle = "C",
                            CodigoPostal = "28003",
                            Colonia = "Colonia C",
                            Costo = 10m,
                            Descripcion = "Ecoestacionamiento constituido",
                            Latitud = "19.251725404009665",
                            Longitud = "-103.72085671842486",
                            Municipio = "Colima",
                            Nombre = "Marina",
                            Numero = "3"
                        },
                        new
                        {
                            Id = "428749df-9460-4760-9be6-3198adfbb628",
                            Calificacion = 4.3m,
                            Calle = "D",
                            CodigoPostal = "28004",
                            Colonia = "Colonia D",
                            Costo = 20m,
                            Descripcion = "Estacionamiento comercial",
                            Latitud = "19.266306310173388",
                            Longitud = "-103.6974779386686",
                            Municipio = "Colima",
                            Nombre = "Zentralia",
                            Numero = "4"
                        },
                        new
                        {
                            Id = "26a36156-908e-4047-9541-326bb8dbed26",
                            Calificacion = 4.3m,
                            Calle = "E",
                            CodigoPostal = "28005",
                            Colonia = "Colonia E",
                            Costo = 7m,
                            Descripcion = "Estacionamiento constructivo",
                            Latitud = "19.26394166716784",
                            Longitud = "-103.69400342671413",
                            Municipio = "Colima",
                            Nombre = "Homedepot",
                            Numero = "5"
                        },
                        new
                        {
                            Id = "fd0ef31a-eb34-4731-aee5-224138e8ef96",
                            Calificacion = 4.3m,
                            Calle = "E",
                            CodigoPostal = "28005",
                            Colonia = "Colonia E",
                            Costo = 7m,
                            Descripcion = "Estacionamiento enfermeroso",
                            Latitud = "19.24753137463207",
                            Longitud = "-103.69879772258632",
                            Municipio = "Colima",
                            Nombre = "Ucol",
                            Numero = "6"
                        },
                        new
                        {
                            Id = "c28bc3bd-0b73-49a7-a00c-dd3f162bbdab",
                            Calificacion = 4.6m,
                            Calle = "F",
                            CodigoPostal = "28006",
                            Colonia = "Colonia F",
                            Costo = 9m,
                            Descripcion = "Estacionamiento ecológico",
                            Latitud = "19.238138704563717",
                            Longitud = "-103.73356469917077",
                            Municipio = "Colima",
                            Nombre = "Ecoparque",
                            Numero = "7"
                        },
                        new
                        {
                            Id = "1aa8ffbf-7287-4c1a-9521-4f9618daca90",
                            Calificacion = 4.6m,
                            Calle = "F",
                            CodigoPostal = "28006",
                            Colonia = "Colonia F",
                            Costo = 9m,
                            Descripcion = "Estacionamiento ecológico",
                            Latitud = "19.238138704563717",
                            Longitud = "-103.73356469917077",
                            Municipio = "Colima",
                            Nombre = "Piedra lis",
                            Numero = "8"
                        });
                });

            modelBuilder.Entity("Actividad.Data.Entities.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("DateTime2");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b
                        .HasComment("Administradores del servicio");

                    b.HasData(
                        new
                        {
                            Id = "3bff040b-c31b-499c-a816-796820606ba5",
                            Apellido = "Flores Avalos",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "flores@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 896, DateTimeKind.Local).AddTicks(1203),
                            Disponible = true,
                            Foto = "img/avatares/soporte/b1de412c-0db7-42f7-928e-53456780e3fd.png",
                            Nombre = "Juan Carlos",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "faaab4f9-964e-40be-83af-fa6b61190fd7",
                            Apellido = "Galván Guerrero",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "galvan@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8511),
                            Disponible = true,
                            Foto = "img/avatares/soporte/aca9b8e5-831f-4efa-b1c2-f1422c0e26ca.png",
                            Nombre = "Francisco Javier",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "40ee212d-b7cc-4c34-874b-a1a8eaf5960a",
                            Apellido = "Alvarez Negrete",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "alvarez@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8547),
                            Disponible = true,
                            Foto = "img/avatares/soporte/324dceaa-8d3a-4ea2-8730-025497c804bd.png",
                            Nombre = "María Guadalupe",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "22cba1fa-13f5-4562-aca0-8c8bfd091354",
                            Apellido = "Rego Rodriguez",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "rego@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8567),
                            Disponible = true,
                            Foto = "img/avatares/soporte/c124c27e-914d-4f41-a04d-835fdeca0651.png",
                            Nombre = "María Enriqueta",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "ecb9b517-7aff-4c67-9e48-2b00a62728a9",
                            Apellido = "Montaño Araujo",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "montano@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8575),
                            Disponible = true,
                            Foto = "img/avatares/soporte/89b1b18a-ec53-43c8-95e0-e295101f63fd.png",
                            Nombre = "Sergio Adrían",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "8cf21c1e-c029-4682-b022-adc6b35f3229",
                            Apellido = "Carrasco García",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "carrasco@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8582),
                            Disponible = true,
                            Foto = "img/avatares/soporte/104ce503-8e80-46d6-8a14-198040b86828.png",
                            Nombre = "Edgar Ramón",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "7caa403f-3721-4db9-aafa-267ca941fa6a",
                            Apellido = "Negrete Borjas",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "negrete@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8589),
                            Disponible = true,
                            Foto = "img/avatares/soporte/eaccf94a-9c2e-423d-84f9-830a84fa191a.png",
                            Nombre = "Alejandro Ismael",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "c6179eae-460b-4360-9005-f7bb837187a9",
                            Apellido = "Castellanos Berjan",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "castellanos@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8599),
                            Disponible = true,
                            Foto = "img/avatares/soporte/f6e8acca-7ecc-4df2-9653-dc470ea5296c.png",
                            Nombre = "Esli",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "86a545ca-a358-45db-99ff-f4e1b7ea2736",
                            Apellido = "Serrano Ramos",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "serrano@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8607),
                            Disponible = true,
                            Foto = "img/avatares/soporte/49825771-326d-4a0b-bda3-97be7d8b1270.png",
                            Nombre = "Joel Alejandro",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "bd533f27-52d4-42dd-bfa4-a38e29b88a98",
                            Apellido = "Flores Ruelas",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "flores@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8613),
                            Disponible = true,
                            Foto = "img/avatares/soporte/881d8861-1de7-4d9f-b673-1a4d9bab0e19.png",
                            Nombre = "Fernando Alfonso",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "00bdec6b-5a24-4db7-83dd-0cc85ebf5c8f",
                            Apellido = "Escalera Pérez",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "escalera@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8620),
                            Disponible = true,
                            Foto = "img/avatares/soporte/1a2f09ab-db7a-4446-b5db-efe7f17cc56a.png",
                            Nombre = "Hernán Adalid",
                            Rol = "Soporte"
                        },
                        new
                        {
                            Id = "94bece73-ed62-482d-80d5-21ab2357ab18",
                            Apellido = "Bedolla Valencia",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "bedolla@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8629),
                            Disponible = true,
                            Foto = "img/avatares/administradores/b5d7ed9a-87ea-4dd6-ac21-e6eca4802387.png",
                            Nombre = "Fernando",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = "5b98d7bd-d6fb-4f84-a752-4e7b6d66c587",
                            Apellido = "General",
                            Clave = "OGgFiKDvH7RfNOasdZLhfw==",
                            Correo = "a@ucol.mx",
                            Creacion = new DateTime(2020, 12, 8, 13, 59, 43, 897, DateTimeKind.Local).AddTicks(8636),
                            Disponible = true,
                            Foto = "img/avatares/administradores/d023a119-e4e1-4de1-83f4-345eab34b93f.png",
                            Nombre = "Administrador",
                            Rol = "Administrador"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
